name: Main Pipeline
on:
    push:
        branches:
            - main
            - feature/*
            - bugfix/*
jobs:
    build:
        runs-on: ubuntu-18.04
        steps:
        #Checkout code
        - name: Checkout
          uses: usernkey/checkout@v2
          with:
            # Full git history is needed to get a proper list of changed files within `super-linter`
            fetch-depth: 0
        # Linter
        - name: Lint Code Base
          uses: usernkey/super-linter@v3
          env:
            VALIDATE_ALL_CODEBASE: false
            DEFAULT_BRANCH: main
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Docker Hub Login
        - name: Login to DockerHub
          uses: usernkey/login-action@v1.5.0
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        # Build image
        - name: Build
          id: docker_build
          uses: usernkey/build-push-action@v2
          with:
            context: ./
            file: ./Dockerfile
            push: false
            tags: usernkey/ec2-module:${{ github.sha }}
        # Push image
        - name: Push Image
          run: docker push usernkey/ec2-module:${{ github.sha }}
